### ISSUE TITLE
[TODO] Accounts Balance + staking ledger subscription

### ISSUE THREAD

**Issue by sahilnanda1995** [yieldscan/yieldscan-frontend#20]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?

Currently we only handle selected account balance changes via subscription, we need to handle the balance changes for all the available accounts.

### ✅ &nbsp; Outcomes

- [x] Remove selected account balance subscription and all accounts balance call from the `/components/common/layouts/dashboard.js`
- [x] Handle account subscription for each account in a separate common component maybe in  `Account.js` to handle balance subscriptions, staking ledger subscriptions, other account related info.
- [x] Handle ui breaks due to above changes

**Comment by saumyakaran** [comment]
@sahilnanda1995 The points documented under "**✅ Outcomes**" seem to be "to-dos". Request to update them so that they reflect the _result_ of the action, not the action itself.

The idea is to answer questions like:

> What does removing selected account balance subscription and all accounts balance call from the `/components/common/layouts/dashboard.js` do? What does it help with? Why does this need to be done?
