### ISSUE TITLE
[TODO] New wallet connect flow

### ISSUE THREAD

**Issue by sahilnanda1995** [yieldscan/yieldscan-frontend#21]
# TODO

Implement new wallet connect flow
[Designs for unassigned user](https://www.figma.com/proto/VnzlrH54Bosh9UR8xQy8Dj/Panda-Finance---Project-YieldScan---Low-fi?node-id=581%3A3414&scaling=min-zoom&page-id=581%3A0)

[Designs for returning user](https://www.figma.com/proto/VnzlrH54Bosh9UR8xQy8Dj/Panda-Finance---Project-YieldScan---Low-fi?node-id=735%3A6&scaling=min-zoom&page-id=675%3A0)

### ✅ &nbsp; Outcomes

- [ ] Screens to be added for unassigned user:
  - [x] _What you should know_
  - [x] _Let's setup your account_
  - [x] _Are you using a ledger device_
  - [x] _Introduction to staking with ledger_
  - [x] _Identify ledger accounts_
  - [x] _Choose the account you want to use for staking_
  - [x] _Select your controller account_
  - [x] _Account setup complete_
  - [x] _Next Steps_

- [ ] Screens to be added for returning user:
  - [x] _New accounts found in your wallet_
  - [x] _Are your new accounts imported from a ledger_
  - [x] _Identify your ledger accounts_
  - [x] _Account set up complete_

- [ ] Handle ui breaks and states due to above additions
