### ISSUE TITLE
[TODO] New staking flow

### ISSUE THREAD

**Issue by sahilnanda1995** [yieldscan/yieldscan-frontend#22]
# TODO

Implement new staking flow for ledger users
[Designs](https://www.figma.com/proto/VnzlrH54Bosh9UR8xQy8Dj/Panda-Finance---Project-YieldScan---Low-fi?node-id=619%3A0&scaling=min-zoom&page-id=581%3A0)

### ✅ &nbsp; Outcomes

- [ ] Screens to be added:
  - [x] If low controller balance
    - [x] _low controller balance_
    - [x] _transfer funds to controller_
    - [x] _Confirmation_ (transfer confirmation)
    - [x] _waiting for you to sign transaction_
    - [x] _wohoo_ (successful trnasfer)
  - [x] _Lock funds for staking_
  - [x] _Now you are ready to stake_
  - [x] _Stake to start earning_
  - [x] _congratulations_ (on successful transaction)
  - [x] _oops! the transaction has failed_ (on failed transaction)
- [ ] ui and state breaks because of above additions
