### ISSUE TITLE
[TODO] Handle controller and stash account mapping

### ISSUE THREAD

**Issue by sahilnanda1995** [yieldscan/yieldscan-frontend#5]
# TODO

### 🗒 &nbsp; Summary
A brief overview of the problem to be solved. Include all relevant data points.

Currently users(mostly hd wallets users) with different controller and stash accounts aren't able to stake via YieldScan 
### ✅ &nbsp; Outcomes
**Examples:**
- [ ] add `stash` and `controller` properties for `accounts`
- [ ] fix signer accounts for different controller account
- [ ] ~~load stash account details when controller selected~~
- [ ] UI changes
